pygments: true
permalink: pretty
paginate: 10
paginate_path: 'page/:num'

excerpt_separator: '\n\n\n'
exclude: ['README.md', 'LICENSE', 'Rakefile']
timezone: 'America/Vancouver'

url: 'http://howardlu.com'

tag_page_title: 'Archive: ":tag"'
tag_page_description: 'Posts by Howard Lu archived under ":tag"'
